package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"ultimate-sdd-framework/internal/agents"
	"ultimate-sdd-framework/internal/gates"
)

func NewExecuteCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "execute",
		Short: "Begin implementation using the Developer agent",
		Long: `Start implementing the approved tasks.

This command uses the Developer agent to guide the implementation
process and track progress against the task breakdown.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Check project state
			stateMgr := gates.NewStateManager(".")
			state, err := stateMgr.LoadState()
			if err != nil {
				return fmt.Errorf("project not initialized: %w", err)
			}

			if state.CurrentPhase != gates.PhaseTask {
				return fmt.Errorf("cannot execute: current phase is %s (need %s)", state.CurrentPhase, gates.PhaseTask)
			}

			// Check if tasks exist
			taskPath := stateMgr.GetPhaseOutputPath(gates.PhaseTask)
			if _, err := os.Stat(taskPath); os.IsNotExist(err) {
				return fmt.Errorf("tasks not found: %s", taskPath)
			}

			// Load tasks
			taskContent, err := os.ReadFile(taskPath)
			if err != nil {
				return fmt.Errorf("failed to read tasks: %w", err)
			}

			// Initialize agent service
			agentSvc := agents.NewAgentService(".")
			if err := agentSvc.Initialize(); err != nil {
				return fmt.Errorf("failed to initialize agent service: %w", err)
			}

			// Get developer agent
			devAgent, err := agentSvc.GetAgentForPhase("execute")
			if err != nil {
				return fmt.Errorf("developer agent not available: %w", err)
			}

			// Transition to execute phase
			if err := stateMgr.TransitionPhase(gates.PhaseExecute, "developer"); err != nil {
				return fmt.Errorf("failed to transition to execute phase: %w", err)
			}

			// Generate implementation guide
			implContent := generateImplementationGuide(devAgent, string(taskContent))

			// Save implementation guide
			implPath := stateMgr.GetPhaseOutputPath(gates.PhaseExecute)
			if err := os.WriteFile(implPath, []byte(implContent), 0644); err != nil {
				return fmt.Errorf("failed to save implementation guide: %w", err)
			}

			// Complete phase (in real implementation, this would track actual progress)
			if err := stateMgr.CompletePhase([]string{"implementation.md"}); err != nil {
				return fmt.Errorf("failed to complete execute phase: %w", err)
			}

			fmt.Printf("✅ Implementation phase started: %s\n", implPath)
			fmt.Println("Next: Work through the implementation tasks, then run 'sdd review'")

			return nil
		},
	}

	return cmd
}

func generateImplementationGuide(agent *agents.Agent, context string) string {
	template := `---
title: Implementation Guide
created_by: %s
created_at: Generated by Ultimate SDD Framework
---

# Implementation Guide

## Development Workflow

This guide provides the implementation approach for the approved architecture plan.

### Key Development Practices
- Write tests before implementation (TDD)
- Follow clean code principles
- Implement security by design
- Regular code reviews
- Continuous integration

### Implementation Phases
1. **Foundation**: Database, authentication, core services
2. **Business Logic**: Domain models, API endpoints, business rules
3. **User Interface**: Components, state management, user experience
4. **Quality Assurance**: Testing, security review, performance optimization

### Code Quality Standards
- Functions under 50 lines
- Meaningful names and comments
- Comprehensive error handling
- Security considerations in every component
- 80%%+ test coverage

### Deployment Strategy
- Automated testing in CI/CD
- Staging environment validation
- Gradual rollout with monitoring
- Rollback procedures documented

---
*Generated by %s agent using Ultimate SDD Framework*`

	return fmt.Sprintf(template, agent.Role, agent.Role)
}
