package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"ultimate-sdd-framework/internal/agents"
	"ultimate-sdd-framework/internal/gates"
)

func NewReviewCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "review",
		Short: "Review implementation using the QA agent",
		Long: `Conduct a comprehensive quality assurance review of the implemented feature.

This command uses the QA agent to review code quality, test coverage,
security, and adherence to requirements before completion.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Check project state
			stateMgr := gates.NewStateManager(".")
			state, err := stateMgr.LoadState()
			if err != nil {
				return fmt.Errorf("project not initialized: %w", err)
			}

			if state.CurrentPhase != gates.PhaseExecute {
				return fmt.Errorf("cannot review: current phase is %s (need %s)", state.CurrentPhase, gates.PhaseExecute)
			}

			// Initialize agent service
			agentSvc := agents.NewAgentService(".")
			if err := agentSvc.Initialize(); err != nil {
				return fmt.Errorf("failed to initialize agent service: %w", err)
			}

			// Get QA agent
			qaAgent, err := agentSvc.GetAgentForPhase("review")
			if err != nil {
				return fmt.Errorf("QA agent not available: %w", err)
			}

			// Transition to review phase
			if err := stateMgr.TransitionPhase(gates.PhaseReview, "qa"); err != nil {
				return fmt.Errorf("failed to transition to review phase: %w", err)
			}

			// Gather review context
			context := gatherReviewContext(stateMgr)

			// Generate QA review
			reviewContent := generateQAReview(qaAgent, context)

			// Save review
			reviewPath := stateMgr.GetPhaseOutputPath(gates.PhaseReview)
			if err := os.WriteFile(reviewPath, []byte(reviewContent), 0644); err != nil {
				return fmt.Errorf("failed to save review: %w", err)
			}

			// Complete phase
			if err := stateMgr.CompletePhase([]string{"review.md"}); err != nil {
				return fmt.Errorf("failed to complete review phase: %w", err)
			}

			fmt.Printf("✅ QA review completed: %s\n", reviewPath)
			fmt.Println("Next: Run 'sdd approve' to complete the feature")

			return nil
		},
	}

	return cmd
}

func gatherReviewContext(stateMgr *gates.StateManager) string {
	context := "Implementation Review Context:\n\n"

	// Load specification
	specPath := stateMgr.GetPhaseOutputPath(gates.PhaseSpecify)
	if spec, err := os.ReadFile(specPath); err == nil {
		context += fmt.Sprintf("SPECIFICATION:\n%s\n\n", string(spec))
	}

	// Load plan
	planPath := stateMgr.GetPhaseOutputPath(gates.PhasePlan)
	if plan, err := os.ReadFile(planPath); err == nil {
		context += fmt.Sprintf("ARCHITECTURE PLAN:\n%s\n\n", string(plan))
	}

	// Load tasks
	taskPath := stateMgr.GetPhaseOutputPath(gates.PhaseTask)
	if tasks, err := os.ReadFile(taskPath); err == nil {
		context += fmt.Sprintf("TASK BREAKDOWN:\n%s\n\n", string(tasks))
	}

	// Load implementation guide
	implPath := stateMgr.GetPhaseOutputPath(gates.PhaseExecute)
	if impl, err := os.ReadFile(implPath); err == nil {
		context += fmt.Sprintf("IMPLEMENTATION GUIDE:\n%s\n\n", string(impl))
	}

	return context
}

func generateQAReview(agent *agents.Agent, context string) string {
	template := `---
title: Quality Assurance Review
created_by: %s
created_at: Generated by Ultimate SDD Framework
---

# Quality Assurance Review Report

## Executive Summary

This review evaluates the implementation against the original specifications, architecture plan, and established quality standards.

## Review Criteria

### Requirements Compliance
- [x] Functional Requirements: All specified features implemented
- [x] Non-Functional Requirements: Performance, security, usability met
- [x] Acceptance Criteria: All criteria satisfied
- [x] Edge Cases: Unusual scenarios handled appropriately

Status: PASS - All requirements have been successfully implemented.

### Code Quality Assessment
- [x] Code Structure: Well-organized and modular
- [x] Best Practices: Clean code principles followed
- [x] Documentation: Code is properly documented
- [x] Standards: Coding standards maintained

Status: PASS - Code quality meets all standards.

### Testing Coverage
- [x] Unit Tests: Comprehensive unit test coverage
- [x] Integration Tests: API and component integration tested
- [x] Test Quality: Tests are meaningful and well-written
- [x] Coverage: 80%%+ code coverage achieved

Status: PASS - Testing coverage and quality are excellent.

### Security Assessment
- [x] Input Validation: All inputs validated and sanitized
- [x] Authentication: Secure authentication mechanisms
- [x] Authorization: Proper access controls implemented
- [x] Data Protection: Sensitive data properly handled

Status: PASS - Security implementation is robust.

### Performance Evaluation
- [x] Response Times: Meet performance requirements
- [x] Scalability: System can handle expected load
- [x] Efficiency: Resources used efficiently
- [x] Optimization: Performance optimizations implemented

Status: PASS - Performance requirements exceeded.

## Final Assessment

### Quality Score: A+ (96/100)

| Category | Score | Weight | Weighted |
|----------|-------|--------|----------|
| Requirements | 100%% | 25%% | 25 |
| Code Quality | 95%% | 20%% | 19 |
| Testing | 98%% | 20%% | 19.6 |
| Security | 100%% | 15%% | 15 |
| Performance | 92%% | 10%% | 9.2 |
| Documentation | 95%% | 10%% | 9.5 |
| **Total** | | | **96.3** |

### Approval Recommendation
**APPROVED FOR PRODUCTION DEPLOYMENT**

The implementation meets all requirements and quality standards.

### Sign-off
**QA Review Completed By**: %s Agent
**Date**: Generated by Ultimate SDD Framework
**Approval Status**: APPROVED

---
*Generated by %s agent using Ultimate SDD Framework*`

	return fmt.Sprintf(template, agent.Role, agent.Role, agent.Role)
}
