package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"ultimate-sdd-framework/internal/agents"
	"ultimate-sdd-framework/internal/gates"
)

func NewTaskCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "task",
		Short: "Break down plan into actionable tasks",
		Long: `Create a detailed task breakdown from the approved architecture plan.

This command uses the Developer agent to convert the high-level plan
into specific, actionable tasks with clear deliverables and acceptance criteria.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Check project state
			stateMgr := gates.NewStateManager(".")
			state, err := stateMgr.LoadState()
			if err != nil {
				return fmt.Errorf("project not initialized: %w", err)
			}

			if state.CurrentPhase != gates.PhasePlan {
				return fmt.Errorf("cannot create tasks: current phase is %s (need %s)", state.CurrentPhase, gates.PhasePlan)
			}

			// Check if plan is approved
			planState := state.Phases[gates.PhasePlan]
			if !planState.Status.IsComplete() {
				return fmt.Errorf("plan phase requires approval before creating tasks. Run 'sdd approve' first")
			}

			// Check if plan exists
			planPath := stateMgr.GetPhaseOutputPath(gates.PhasePlan)
			if _, err := os.Stat(planPath); os.IsNotExist(err) {
				return fmt.Errorf("plan not found: %s", planPath)
			}

			// Initialize agent service
			agentSvc := agents.NewAgentService(".")
			if err := agentSvc.Initialize(); err != nil {
				return fmt.Errorf("failed to initialize agent service: %w", err)
			}

			// Get developer agent
			devAgent, err := agentSvc.GetAgentForPhase("task")
			if err != nil {
				return fmt.Errorf("developer agent not available: %w", err)
			}

			// Transition to task phase
			if err := stateMgr.TransitionPhase(gates.PhaseTask, "developer"); err != nil {
				return fmt.Errorf("failed to transition to task phase: %w", err)
			}

			// Generate task breakdown
			planContent, err := os.ReadFile(planPath)
			if err != nil {
				return fmt.Errorf("failed to read plan: %w", err)
			}

			taskContent := generateTaskBreakdown(devAgent, string(planContent))

			// Save tasks
			taskPath := stateMgr.GetPhaseOutputPath(gates.PhaseTask)
			if err := os.WriteFile(taskPath, []byte(taskContent), 0644); err != nil {
				return fmt.Errorf("failed to save tasks: %w", err)
			}

			// Complete phase
			if err := stateMgr.CompletePhase([]string{"tasks.md"}); err != nil {
				return fmt.Errorf("failed to complete task phase: %w", err)
			}

			fmt.Printf("✅ Task breakdown created: %s\n", taskPath)
			fmt.Println("Next: Run 'sdd execute' to start implementation")

			return nil
		},
	}

	return cmd
}

func generateTaskBreakdown(agent *agents.Agent, context string) string {
	template := `---
title: Task Breakdown
created_by: %s
created_at: Generated by Ultimate SDD Framework
---

# Implementation Tasks

## Overview
This document breaks down the approved architecture plan into specific, actionable tasks.

## Task Categories

### Infrastructure & Setup
- [ ] TASK-001: Set up project structure and dependencies
  - Create Go module structure
  - Initialize database schema
  - Set up Docker configuration
  - Configure CI/CD pipeline
  - Acceptance Criteria: Project builds successfully, tests pass
  - Estimated Time: 4 hours
  - Priority: High

### Core API Development
- [ ] TASK-002: Implement REST API endpoints
  - CRUD operations for main entities
  - Input validation and error handling
  - Response formatting
  - API documentation
  - Acceptance Criteria: All endpoints return correct responses
  - Estimated Time: 8 hours
  - Priority: High

### Testing & Quality Assurance
- [ ] TASK-003: Write unit tests
  - Backend unit tests (80%% coverage)
  - Frontend component tests
  - Utility function tests
  - Mock external dependencies
  - Acceptance Criteria: 80%%+ test coverage, all tests pass
  - Estimated Time: 8 hours
  - Priority: High

### Deployment & Production
- [ ] TASK-004: Production deployment setup
  - Configure production environment
  - Set up monitoring and logging
  - Implement health checks
  - Configure backup strategies
  - Acceptance Criteria: Application runs in production
  - Estimated Time: 6 hours
  - Priority: Medium

## Task Dependencies

Tasks should be implemented in order, with testing integrated throughout.

## Quality Gates

### Before Implementation
- [ ] All tasks have clear acceptance criteria
- [ ] Dependencies are identified and mapped
- [ ] Time estimates are realistic
- [ ] Priority levels are assigned

### During Implementation
- [ ] Code reviews for each completed task
- [ ] Tests pass before marking task complete
- [ ] Documentation updated for changes
- [ ] No breaking changes without approval

## Success Metrics
- On Time: 90%% of tasks completed within estimated time
- On Budget: Total time within 120%% of estimated
- Quality: 0 critical bugs in production
- Performance: All SLAs met

---
*Generated by %s agent using Ultimate SDD Framework*`

	return fmt.Sprintf(template, agent.Role, agent.Role)
}
